// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbv5bETgIoyhFqlwl_FRDdlOAbMfd41v4',
    appId: '1:972297666969:web:5822e7d9895fe398015308',
    messagingSenderId: '972297666969',
    projectId: 'allergyawayauth-94d00',
    authDomain: 'allergyawayauth-94d00.firebaseapp.com',
    storageBucket: 'allergyawayauth-94d00.appspot.com',
    measurementId: 'G-QZXTYRCJYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf5XoKqBlUv1ysiX2WB_v55USHudahn4Q',
    appId: '1:972297666969:android:4a5057750c52ce05015308',
    messagingSenderId: '972297666969',
    projectId: 'allergyawayauth-94d00',
    storageBucket: 'allergyawayauth-94d00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIYHk0IVDSjFXk9gjgzhzLkyTOjRXMigM',
    appId: '1:972297666969:ios:578378350e0a0776015308',
    messagingSenderId: '972297666969',
    projectId: 'allergyawayauth-94d00',
    storageBucket: 'allergyawayauth-94d00.appspot.com',
    iosBundleId: 'com.example.demo2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIYHk0IVDSjFXk9gjgzhzLkyTOjRXMigM',
    appId: '1:972297666969:ios:e607efff846397b1015308',
    messagingSenderId: '972297666969',
    projectId: 'allergyawayauth-94d00',
    storageBucket: 'allergyawayauth-94d00.appspot.com',
    iosBundleId: 'com.example.demo2.RunnerTests',
  );
}
